### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Line does not match regex

### ISSUE THREAD

**Issue by matthewstifler** [matthewjdenny/SpeedReader#2]
I'm getting this error on running `mallet_lda` with following parameters:
```
iterations = 1500,
hyperparameter_optimization_interval = 10,
tokenization_regex = "[\\p{L}\\p{N}-]*\\p{L}+",
cores = 8,
stopword_list = readLines(stoplist.file),
delete_intermediate_files = TRUE
```

This is the output I get in console:
```
Found MALLET JAR files...
Outputing documents in correct format for MALLET...
Writing corpus to file...Converting input to MALLET format...
Exception in thread "main" java.lang.IllegalStateException: Line #45979 does not match regex:
[Line 45979 contents]
	at cc.mallet.pipe.iterator.CsvIterator.next(CsvIterator.java:95)
	at cc.mallet.pipe.iterator.CsvIterator.next(CsvIterator.java:44)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:291)
	at cc.mallet.pipe.Pipe$SimplePipeInstanceIterator.next(Pipe.java:283)
	at cc.mallet.types.InstanceList.addThruPipe(InstanceList.java:267)
	at cc.mallet.classify.tui.Csv2Vectors.main(Csv2Vectors.java:290)
Fitting topic model. This may take anywhere from seconds to days depending on the size of your corpus. Check: pathToProjectFolder/mallet_intermediate_files/mallet_intermediate_files/stdout.txt for estimation progress...
Reading MALLET output back into R...
Error: XML content does not seem to be XML: 'topic-report.xml'
```
Here is what gets written to `stdout.txt`, after function call fails:

```
java.io.FileNotFoundException: mallet_corpus.dat
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at cc.mallet.types.InstanceList.load(InstanceList.java:787)
	at cc.mallet.topics.tui.Vectors2Topics.main(Vectors2Topics.java:403)
Unable to restore instance list mallet_corpus.dat: java.lang.IllegalArgumentException: Couldn't read InstanceList from file mallet_corpus.dat
```
My wild guess is that it has something to do with my data, so I can share it with you, if that would be necessary. However, I haven't encountered this kind of behavior with any data before. 
I found out that it has nothing to do with number of cores, stoplist, number of topics, iterations, or tokenization regex (tried to change it to '[\\pL]+').

Here is my `sessionInfo()` output:
```
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=ru_RU.UTF-8       LC_NUMERIC=C               LC_TIME=ru_RU.UTF-8        LC_COLLATE=ru_RU.UTF-8    
 [5] LC_MONETARY=ru_RU.UTF-8    LC_MESSAGES=ru_RU.UTF-8    LC_PAPER=ru_RU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=ru_RU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.2       SpeedReader_0.7.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12      XML_3.98-1.9      assertthat_0.2.0  slam_0.1-40       R6_2.2.2          magrittr_1.5     
 [7] rlang_0.1.1       bindrcpp_0.2      tools_3.3.1       snowfall_1.84-6.1 glue_1.1.1        parallel_3.3.1   
[13] rsconnect_0.4.3   pkgconfig_2.0.1   bindr_0.1         tibble_1.3.3     
```
Also, `java -version` output, even though I have no idea if it might help:
```
java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.151-b01, mixed mode)
```

Thanks in advance for looking into this!

Also, can't help but want to express my gratitude for this package, it helps me a lot and it also performs great and flawlessly! Training LDA in parallel is the killer feature for me. No idea what I would have to do without it.

**Comment by matthewstifler** [comment]
Ok, that was pretty silly of me: there actually were some weird symbols on a few lines that broke running of LDA. I removed those lines and everything went back to normal. I'll close this issue now.
